using DecoratR.Generator.Detection;
using DecoratR.Generator.Model;

namespace DecoratR.Generator.Emit;

/// <summary>
/// Emits the per-assembly decorator registry with one public generic apply method per decorator, plus the
/// <c>[DecoratRDecorator]</c> assembly attributes consumed by composition roots.
/// </summary>
internal static class DecoratorRegistryEmitter
{
    public const string HintName = "DecoratRDecoratorRegistry.g.cs";

    public static string RegistryType(AssemblyInfo assembly) =>
        "global::" + assembly.Namespace + "." + WellKnownTypes.DecoratorRegistryClassName;

    public static string Generate(AssemblyInfo assembly, EquatableArray<DecoratorMetadata> decorators)
    {
        var methodNames = ApplyMethodNames(decorators);
        var registryType = RegistryType(assembly);

        var w = new SourceWriter(2048 + decorators.Length * 900);
        w.AppendFileHeader();

        for (var i = 0; i < decorators.Length; i++)
            WriteDecoratorAttribute(w, registryType + "." + methodNames[i], decorators[i]);

        w.AppendLine();
        w.Append("namespace ").Append(assembly.Namespace).AppendLine(";");
        w.AppendLine();

        w.AppendLine("/// <summary>");
        w.Append("/// Decorator registry generated by DecoratR for assembly <c>").AppendXmlEscaped(assembly.Name).AppendLine("</c>.");
        w.AppendLine("/// Infrastructure for cross-assembly composition; not intended for direct use.");
        w.AppendLine("/// </summary>");
        w.AppendGeneratedCodeAttribute(hideFromIntelliSense: true);

        using (w.Block("public static class " + WellKnownTypes.DecoratorRegistryClassName))
        {
            for (var i = 0; i < decorators.Length; i++)
            {
                if (i > 0) w.AppendLine();
                WriteApplyMethod(w, decorators[i], methodNames[i]);
            }

            w.AppendLine();
            RuntimeHelpersEmitter.WriteWrap(w);
            w.AppendLine();
            RuntimeHelpersEmitter.WriteCreateInnerFactory(w);
        }

        return w.ToString();
    }

    /// <summary>Unique apply method names, derived from the decorator's namespace-qualified type name.</summary>
    public static string[] ApplyMethodNames(EquatableArray<DecoratorMetadata> decorators)
    {
        var names = new string[decorators.Length];
        var used = new HashSet<string>(StringComparer.Ordinal);

        for (var i = 0; i < decorators.Length; i++)
        {
            var baseName = "Apply" + IdentifierSanitizer.FromTypeName(decorators[i].DecoratorType);
            var name = baseName;
            var suffix = 2;
            while (!used.Add(name)) name = baseName + "_" + suffix++;
            names[i] = name;
        }

        return names;
    }

    private static void WriteApplyMethod(SourceWriter w, DecoratorMetadata decorator, string methodName)
    {
        var handlerInterface = WellKnownTypes.HandlerInterface(decorator.IsStream);

        w.AppendLine("/// <summary>");
        w.Append("/// Wraps a <c>").AppendTypeForDoc(handlerInterface).Append("&lt;TRequest, TResponse&gt;</c> registration with <c>")
            .AppendTypeForDoc(decorator.Construct("TRequest", "TResponse")).Append("</c> (Order ").Append(decorator.Order).AppendLine(").");
        w.AppendLine("/// </summary>");
        w.Append("public static ").Append(WellKnownTypes.ServiceDescriptor).Append(' ').Append(methodName)
            .AppendLine("<TRequest, TResponse>(");
        using (w.Indent())
        {
            w.Append(WellKnownTypes.ServiceDescriptor).AppendLine(" inner)");
            ConstraintSerializer.WriteWhereClause(w, "TRequest", decorator.RequestConstraints, "TRequest", "TResponse");
            ConstraintSerializer.WriteWhereClause(w, "TResponse", decorator.ResponseConstraints, "TRequest", "TResponse");
        }

        using (w.Block())
        {
            w.Append("return Wrap<").Append(handlerInterface).Append("<TRequest, TResponse>, ")
                .Append(decorator.Construct("TRequest", "TResponse")).AppendLine(">(inner);");
        }
    }

    private static void WriteDecoratorAttribute(SourceWriter w, string applyMethod, DecoratorMetadata decorator)
    {
        w.Append("[assembly: ").Append(WellKnownTypes.DecoratorMetadataAttribute).Append('(')
            .AppendQuoted(applyMethod).Append(", ")
            .AppendQuoted(decorator.DecoratorType).Append(", ")
            .Append(decorator.Order).Append(", ")
            .Append(decorator.IsStream ? "true" : "false");

        if (!decorator.RequestConstraints.IsEmpty)
            w.Append(", RequestConstraints = ").AppendQuoted(ConstraintSerializer.Join(decorator.RequestConstraints));

        if (!decorator.ResponseConstraints.IsEmpty)
            w.Append(", ResponseConstraints = ").AppendQuoted(ConstraintSerializer.Join(decorator.ResponseConstraints));

        w.AppendLine(")]");
    }
}
