using DecoratR.Generator.Detection;
using DecoratR.Generator.Model;

namespace DecoratR.Generator.Emit;

/// <summary>
/// Emits the per-assembly handler registry and the <c>[DecoratRRegistry]</c>/<c>[DecoratRHandler]</c>
/// assembly attributes consumed by composition roots.
/// </summary>
internal static class HandlerRegistryEmitter
{
    public const string HintName = "DecoratRHandlerRegistry.g.cs";

    public static string RegistryType(AssemblyInfo assembly) =>
        "global::" + assembly.Namespace + "." + WellKnownTypes.HandlerRegistryClassName;

    public static string Generate(AssemblyInfo assembly, EquatableArray<HandlerMetadata> handlers)
    {
        var w = new SourceWriter(1024 + handlers.Length * 700);
        w.AppendFileHeader();

        w.Append("[assembly: ").Append(WellKnownTypes.RegistryAttribute).Append('(')
            .AppendQuoted(RegistryType(assembly)).AppendLine(")]");
        foreach (var handler in handlers) WriteHandlerAttribute(w, handler);

        w.AppendLine();
        w.Append("namespace ").Append(assembly.Namespace).AppendLine(";");
        w.AppendLine();

        w.AppendLine("/// <summary>");
        w.Append("/// Handler registry generated by DecoratR for assembly <c>").AppendXmlEscaped(assembly.Name).AppendLine("</c>.");
        w.AppendLine("/// Infrastructure for cross-assembly composition; not intended for direct use.");
        w.AppendLine("/// </summary>");
        w.AppendGeneratedCodeAttribute(hideFromIntelliSense: true);

        using (w.Block("public static class " + WellKnownTypes.HandlerRegistryClassName))
        {
            w.AppendLine("/// <summary>");
            w.Append("/// ").Append(handlers.Length).AppendLine(" handler(s) discovered in this assembly:");
            w.AppendLine("/// <list type=\"bullet\">");
            foreach (var handler in handlers)
                w.Append("/// <item><description><c>").AppendTypeForDoc(handler.HandlerType)
                    .Append("</c> implements <c>").AppendTypeForDoc(handler.ServiceType.ConstructedInterface)
                    .AppendLine("</c></description></item>");
            w.AppendLine("/// </list>");
            w.AppendLine("/// </summary>");

            using (w.Block("public static HandlerRegistration[] Handlers { get; } =", opening: "[", closing: "];"))
            {
                foreach (var handler in handlers)
                {
                    w.Append("new(typeof(").Append(handler.ServiceType.ConstructedInterface)
                        .Append("), typeof(").Append(handler.HandlerType).AppendLine(")),");

                    // Handlers without a response are also exposed as IRequestHandler<TRequest>; the facade
                    // resolves the decorated IRequestHandler<TRequest, Unit> pipeline.
                    if (handler.RegistersVoidFacade)
                        w.Append("new(typeof(").Append(handler.VoidFacadeInterface)
                            .Append("), typeof(").Append(handler.VoidFacadeImplementation).AppendLine(")),");
                }
            }

            w.AppendLine();
            w.AppendLine("/// <summary>The service type and implementation type of one registered handler.</summary>");
            w.AppendLine("public sealed record HandlerRegistration(");
            using (w.Indent())
            {
                w.Append(WellKnownTypes.Type).AppendLine(" ServiceType,");
                w.Append('[').Append(WellKnownTypes.DynamicallyAccessedPublicConstructors).Append("] [property: ")
                    .Append(WellKnownTypes.DynamicallyAccessedPublicConstructors).Append("] ")
                    .Append(WellKnownTypes.Type).AppendLine(" ImplementationType);");
            }
        }

        return w.ToString();
    }

    private static void WriteHandlerAttribute(SourceWriter w, HandlerMetadata handler)
    {
        var service = handler.ServiceType;

        w.Append("[assembly: ").Append(WellKnownTypes.HandlerAttribute).Append('(')
            .AppendQuoted(handler.HandlerType).Append(", ")
            .AppendQuoted(service.RequestType).Append(", ")
            .AppendQuoted(service.ResponseType).Append(", ")
            .Append(service.IsStream ? "true" : "false");

        if (!service.RequestTypeHierarchy.IsEmpty)
            w.Append(", RequestTypeHierarchy = ").AppendQuoted(ConstraintSerializer.Join(service.RequestTypeHierarchy));

        if (!service.ResponseTypeHierarchy.IsEmpty)
            w.Append(", ResponseTypeHierarchy = ").AppendQuoted(ConstraintSerializer.Join(service.ResponseTypeHierarchy));

        if (!service.IsPubliclyAccessible)
            w.Append(", IsPubliclyAccessible = false");

        w.AppendLine(")]");
    }
}
