using System.Globalization;
using System.Text;

namespace DecoratR.Generator.Emit;

/// <summary>
/// Indentation-aware <see cref="StringBuilder"/> wrapper for emitting C# source.
/// </summary>
internal sealed class SourceWriter(int capacity = 2048)
{
    private const int IndentSize = 4;

    private readonly StringBuilder _sb = new(capacity);
    private int _indent;
    private bool _atLineStart = true;

    public SourceWriter Append(string text)
    {
        WriteIndent();
        _sb.Append(text);
        return this;
    }

    public SourceWriter Append(char value)
    {
        WriteIndent();
        _sb.Append(value);
        return this;
    }

    public SourceWriter Append(int value)
    {
        WriteIndent();
        _sb.Append(value.ToString(CultureInfo.InvariantCulture));
        return this;
    }

    public SourceWriter AppendLine(string text)
    {
        WriteIndent();
        _sb.AppendLine(text);
        _atLineStart = true;
        return this;
    }

    public SourceWriter AppendLine()
    {
        _sb.AppendLine();
        _atLineStart = true;
        return this;
    }

    /// <summary>Appends a C# string literal.</summary>
    public SourceWriter AppendQuoted(string text)
    {
        WriteIndent();
        _sb.Append('"');
        foreach (var ch in text)
        {
            switch (ch)
            {
                case '\\': _sb.Append("\\\\"); break;
                case '"': _sb.Append("\\\""); break;
                case '\r': _sb.Append("\\r"); break;
                case '\n': _sb.Append("\\n"); break;
                default: _sb.Append(ch); break;
            }
        }

        _sb.Append('"');
        return this;
    }

    /// <summary>Appends text for use inside an XML documentation comment.</summary>
    public SourceWriter AppendXmlEscaped(string text)
    {
        WriteIndent();
        foreach (var ch in text)
        {
            switch (ch)
            {
                case '<': _sb.Append("&lt;"); break;
                case '>': _sb.Append("&gt;"); break;
                case '&': _sb.Append("&amp;"); break;
                default: _sb.Append(ch); break;
            }
        }

        return this;
    }

    /// <summary>Appends a type name for XML documentation: without <c>global::</c> and XML-escaped.</summary>
    public SourceWriter AppendTypeForDoc(string fullyQualifiedName) =>
        AppendXmlEscaped(fullyQualifiedName.Replace("global::", string.Empty));

    public SourceWriter AppendFileHeader()
    {
        AppendLine("// <auto-generated>");
        AppendLine("//     This file was generated by DecoratR.Generator.");
        AppendLine("//     Do not edit. Changes will be overwritten on the next build.");
        AppendLine("// </auto-generated>");
        AppendLine("#nullable enable");
        AppendLine("#pragma warning disable CS0612, CS0618 // Type or member is obsolete");
        AppendLine("#pragma warning disable CS8631, CS8634, CS8714 // Nullability of type arguments does not match constraints (nullability is not part of the runtime service type)");
        return AppendLine();
    }

    public SourceWriter AppendGeneratedCodeAttribute(bool hideFromIntelliSense = false)
    {
        Append('[').Append(WellKnownTypes.GeneratedCodeAttribute).Append("(\"DecoratR.Generator\", ")
            .AppendQuoted(GeneratorVersion.Value).AppendLine(")]");

        if (hideFromIntelliSense) Append('[').Append(WellKnownTypes.EditorBrowsableNever).AppendLine("]");

        return this;
    }

    public IndentScope Indent()
    {
        _indent++;
        return new IndentScope(this);
    }

    /// <summary>
    /// Writes an optional header line and an opening brace, indents, and returns a scope that writes the
    /// closing token when disposed.
    /// </summary>
    public BlockScope Block(string? header = null, string opening = "{", string closing = "}")
    {
        if (header is not null) AppendLine(header);
        AppendLine(opening);
        _indent++;
        return new BlockScope(this, closing);
    }

    public override string ToString() => _sb.ToString();

    private void Outdent() => _indent--;

    private void WriteIndent()
    {
        if (!_atLineStart) return;

        _sb.Append(' ', _indent * IndentSize);
        _atLineStart = false;
    }

    public readonly struct IndentScope(SourceWriter writer) : IDisposable
    {
        public void Dispose() => writer.Outdent();
    }

    public readonly struct BlockScope(SourceWriter writer, string closing) : IDisposable
    {
        public void Dispose()
        {
            writer.Outdent();
            writer.AppendLine(closing);
        }
    }
}
