<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\src\DecoratR.Abstractions\DecoratR.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\Examples.ModularMonolith.SharedKernel\Examples.ModularMonolith.SharedKernel.csproj" />
  </ItemGroup>

</Project>
