namespace DecoratR.Generator;

internal static class AttributeEmitter
{
    internal static string GenerateHandlerAttribute() =>
        """
        // <auto-generated />
        #nullable enable

        namespace DecoratR;

        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateHandlerRegistrationsAttribute : global::System.Attribute
        {
        }
        """;

    internal static string GenerateFullAttribute() =>
        """
        // <auto-generated />
        #nullable enable

        namespace DecoratR;

        /// <summary>
        /// Triggers the DecoratR source generator to discover all handlers and decorators in the compilation
        /// and emit an <c>AddDecoratR()</c> extension method on <c>IServiceCollection</c>.
        /// Place this attribute in the composition root assembly (e.g. the web API project).
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDecoratRRegistrationsAttribute : global::System.Attribute
        {
        }
        """;

    internal static string GenerateHandlerRegistrationAttribute() =>
        """
        // <auto-generated />
        #nullable enable

        namespace DecoratR;

        /// <summary>
        /// Assembly-level attribute that encodes the fully qualified class name
        /// of a generated handler registry containing a <c>Handlers</c> property.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
        internal sealed class DecoratRHandlerRegistrationAttribute : global::System.Attribute
        {
            public DecoratRHandlerRegistrationAttribute(string className)
            {
                ClassName = className;
            }

            public string ClassName { get; }
        }
        """;

    internal static string GenerateHandlerServiceTypeAttribute() =>
        """
        // <auto-generated />
        #nullable enable

        namespace DecoratR;

        /// <summary>
        /// Assembly-level attribute that encodes a handler's service type (request/response pair).
        /// Used by the composition root generator to discover service types for decorator application.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
        internal sealed class DecoratRHandlerServiceTypeAttribute : global::System.Attribute
        {
            public DecoratRHandlerServiceTypeAttribute(string requestType, string responseType)
            {
                RequestType = requestType;
                ResponseType = responseType;
            }

            public string RequestType { get; }
            public string ResponseType { get; }
        }
        """;
}