namespace DecoratR.Generator;

internal static class AttributeEmitter
{
    internal static string GenerateMetadataAttribute()
    {
        return """
               // <auto-generated>
               //     This file was generated by DecoratR.Generator.
               //     Do not edit. Changes will be overwritten on the next build.
               // </auto-generated>
               #nullable enable
               #pragma warning disable CS0612, CS0618 // Type or member is obsolete

               namespace DecoratR;

               /// <summary>
               /// Generates handler and decorator metadata for the current assembly.
               /// Apply this to a class library that defines request handlers or decorators but does not own
               /// the final <c>IServiceCollection</c> registration call.
               /// </summary>
               /// <remarks>
               /// DecoratR emits a handler registry and decorator registry plus assembly-level metadata that a
               /// composition root marked with <see cref="GenerateDecoratRRegistrationsAttribute"/> can consume
               /// across assembly boundaries.
               /// </remarks>
               [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
               internal sealed class GenerateDecoratRMetadataAttribute : global::System.Attribute
               {
               }
               """;
    }

    internal static string GenerateFullAttribute()
    {
        return """
               // <auto-generated>
               //     This file was generated by DecoratR.Generator.
               //     Do not edit. Changes will be overwritten on the next build.
               // </auto-generated>
               #nullable enable
               #pragma warning disable CS0612, CS0618 // Type or member is obsolete

               namespace DecoratR;

               /// <summary>
               /// Generates the <c>AddDecoratR()</c> registration entry point for the current composition root.
               /// </summary>
               /// <remarks>
               /// Apply this to the host or startup assembly. DecoratR scans the current compilation and referenced
               /// assemblies for handler metadata, then emits an <c>IServiceCollection</c> extension method that
               /// registers handlers and applies decorators in pipeline order.
               /// </remarks>
               [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
               internal sealed class GenerateDecoratRRegistrationsAttribute : global::System.Attribute
               {
               }
               """;
    }

    internal static string GenerateHandlerRegistrationAttribute()
    {
        return """
               // <auto-generated>
               //     This file was generated by DecoratR.Generator.
               //     Do not edit. Changes will be overwritten on the next build.
               // </auto-generated>
               #nullable enable
               #pragma warning disable CS0612, CS0618 // Type or member is obsolete

               namespace DecoratR;

               /// <summary>
               /// Assembly-level attribute that encodes the fully qualified class name
               /// of a generated handler registry containing a <c>Handlers</c> property.
               /// </summary>
               [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
               internal sealed class DecoratRHandlerRegistrationAttribute : global::System.Attribute
               {
                   public DecoratRHandlerRegistrationAttribute(string className)
                   {
                       ClassName = className;
                   }

                   public string ClassName { get; }
               }
               """;
    }

    internal static string GenerateHandlerServiceTypeAttribute()
    {
        return """
               // <auto-generated>
               //     This file was generated by DecoratR.Generator.
               //     Do not edit. Changes will be overwritten on the next build.
               // </auto-generated>
               #nullable enable
               #pragma warning disable CS0612, CS0618 // Type or member is obsolete

               namespace DecoratR;

               /// <summary>
               /// Assembly-level attribute that encodes a handler's service type (request/response pair).
               /// Used by the composition root generator to discover service types for decorator application.
               /// </summary>
               [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
               internal sealed class DecoratRHandlerServiceTypeAttribute : global::System.Attribute
               {
                   public DecoratRHandlerServiceTypeAttribute(string requestType, string responseType)
                   {
                       RequestType = requestType;
                       ResponseType = responseType;
                   }

                   public string RequestType { get; }
                   public string ResponseType { get; }

                   /// <summary>
                   /// Semicolon-delimited fully qualified type names of interfaces and base types
                   /// implemented by the request type. Used for decorator constraint matching.
                   /// </summary>
                   public string RequestTypeHierarchy { get; init; } = "";
               }
               """;
    }

    internal static string GenerateOptions()
    {
        return """
               // <auto-generated>
               //     This file was generated by DecoratR.Generator.
               //     Do not edit. Changes will be overwritten on the next build.
               // </auto-generated>
               #nullable enable
               #pragma warning disable CS0612, CS0618 // Type or member is obsolete

               namespace DecoratR;

               /// <summary>
               /// Configuration options for DecoratR handler registrations.
               /// </summary>
               
               """ +
               $"[global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"{DecoratRGeneratorVersion.Value}\")]\n" +
               """
               public sealed class DecoratROptions
               {
                   /// <summary>
                   /// The service lifetime used for handler registrations. Default is <see cref="global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient"/>.
                   /// </summary>
                   public global::Microsoft.Extensions.DependencyInjection.ServiceLifetime Lifetime { get; set; } =
                       global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient;
               }
               """;
    }

    internal static string GenerateDecoratorRegistrationAttribute()
    {
        return """
               // <auto-generated>
               //     This file was generated by DecoratR.Generator.
               //     Do not edit. Changes will be overwritten on the next build.
               // </auto-generated>
               #nullable enable
               #pragma warning disable CS0612, CS0618 // Type or member is obsolete

               namespace DecoratR;

               /// <summary>
               /// Assembly-level attribute that records the fully qualified name of a generated
               /// decorator apply method and the decorator's order.
               /// The composition root calls these methods to apply cross-assembly decorators
               /// without directly referencing the (possibly internal) decorator type.
               /// </summary>
               [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
               internal sealed class DecoratRDecoratorRegistrationAttribute : global::System.Attribute
               {
                   public DecoratRDecoratorRegistrationAttribute(string applyMethodName, int order)
                   {
                       ApplyMethodName = applyMethodName;
                       Order = order;
                   }

                   public string ApplyMethodName { get; }
                   public int Order { get; }

                   /// <summary>
                   /// Semicolon-delimited fully qualified type names of the TRequest constraints.
                   /// Empty string means the decorator applies to all request types.
                   /// </summary>
                   public string RequestConstraintTypes { get; init; } = "";
               }
               """;
    }
}