using System.Text;

namespace DecoratR.Generator;

internal static class DecoratorRegistryEmitter
{
    internal static string Generate(string assemblyName, IReadOnlyList<DecoratorMetadata> decorators)
    {
        var sb = new StringBuilder(512 + decorators.Count * 600);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This file was generated by DecoratR.Generator.");
        sb.AppendLine("//     Do not edit. Changes will be overwritten on the next build.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0612, CS0618 // Type or member is obsolete");
        sb.AppendLine();

        // Pre-compute method names to avoid duplicate string allocations
        var methodNames = new string[decorators.Count];
        for (var i = 0; i < decorators.Count; i++)
            methodNames[i] = GetApplyMethodName(decorators[i]);

        // Assembly-level metadata attributes for each decorator
        for (var i = 0; i < decorators.Count; i++)
        {
            var decorator = decorators[i];
            var attributeName = decorator.IsStream
                ? "DecoratRStreamDecoratorRegistration"
                : "DecoratRDecoratorRegistration";

            sb.Append("[assembly: global::DecoratR.").Append(attributeName).Append("(\"")
                .Append(assemblyName).Append(".DecoratRDecoratorRegistry.").Append(methodNames[i])
                .Append("\", ")
                .Append(decorator.Order);

            if (HasNonDefaultConstraints(decorator.RequestConstraintTypes, decorator.IsStream))
            {
                sb.Append(", RequestConstraintTypes = \"");
                AppendSemicolonDelimited(sb, decorator.RequestConstraintTypes);
                sb.Append('"');
            }

            sb.AppendLine(")]");
        }

        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).AppendLine(";");
        sb.AppendLine();

        sb.Append("[global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"")
            .Append(DecoratRGeneratorVersion.Value).AppendLine("\")]");
        sb.AppendLine("public static class DecoratRDecoratorRegistry");
        sb.AppendLine("{");

        // Per-decorator public apply methods
        var hasRegular = false;
        var hasStream = false;
        for (var i = 0; i < decorators.Count; i++)
        {
            if (i > 0) sb.AppendLine();

            if (decorators[i].IsStream)
            {
                EmitStreamApplyMethod(sb, decorators[i], methodNames[i]);
                hasStream = true;
            }
            else
            {
                EmitApplyMethod(sb, decorators[i], methodNames[i]);
                hasRegular = true;
            }
        }

        sb.AppendLine();

        // Shared private core methods
        if (hasRegular) EmitDecorateServiceCore(sb);
        if (hasStream)
        {
            if (hasRegular) sb.AppendLine();
            EmitDecorateStreamServiceCore(sb);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitApplyMethod(StringBuilder sb, DecoratorMetadata decorator, string methodName)
    {
        sb.AppendIndentedLine(1, "/// <summary>");
        sb.Append("    /// Wraps <c>IRequestHandler&lt;TRequest, TResponse&gt;</c> with <c>")
            .AppendStrippedGlobalPrefix(decorator.DecoratorFullyQualifiedName)
            .AppendLine("</c>.");
        sb.AppendIndentedLine(1, "/// </summary>");
        sb.Append("    /// <remarks>Decorator order: <c>").Append(decorator.Order).AppendLine("</c>.</remarks>");
        sb.Append("    public static void ").Append(methodName).AppendLine("<TRequest, TResponse>(");
        sb.AppendIndentedLine(2, "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        EmitWhereClause(sb, decorator.RequestConstraintTypes, "global::DecoratR.IRequest");
        sb.AppendIndentedLine(1, "{");
        sb.Append("        DecorateService<TRequest, TResponse, ")
            .Append(decorator.DecoratorFullyQualifiedName)
            .AppendLine("<TRequest, TResponse>>(services);");
        sb.AppendIndentedLine(1, "}");
    }

    private static void EmitStreamApplyMethod(StringBuilder sb, DecoratorMetadata decorator, string methodName)
    {
        sb.AppendIndentedLine(1, "/// <summary>");
        sb.Append("    /// Wraps <c>IStreamRequestHandler&lt;TRequest, TResponse&gt;</c> with <c>")
            .AppendStrippedGlobalPrefix(decorator.DecoratorFullyQualifiedName)
            .AppendLine("</c>.");
        sb.AppendIndentedLine(1, "/// </summary>");
        sb.Append("    /// <remarks>Decorator order: <c>").Append(decorator.Order).AppendLine("</c>.</remarks>");
        sb.Append("    public static void ").Append(methodName).AppendLine("<TRequest, TResponse>(");
        sb.AppendIndentedLine(2, "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        EmitWhereClause(sb, decorator.RequestConstraintTypes, "global::DecoratR.IStreamRequest");
        sb.AppendIndentedLine(1, "{");
        sb.Append("        DecorateStreamService<TRequest, TResponse, ")
            .Append(decorator.DecoratorFullyQualifiedName)
            .AppendLine("<TRequest, TResponse>>(services);");
        sb.AppendIndentedLine(1, "}");
    }

    private static void EmitWhereClause(StringBuilder sb, EquatableArray<string> constraintTypes, string defaultConstraint)
    {
        // Find the most specific constraint (not the default marker itself)
        string? specificConstraint = null;
        foreach (var constraint in constraintTypes)
        {
            if (constraint == "global::DecoratR.IRequest" || constraint == "global::DecoratR.IStreamRequest") continue;
            specificConstraint = constraint;
            break;
        }

        // Use the specific constraint if available, otherwise fall back to the default
        sb.Append("        where TRequest : ")
            .AppendLine(specificConstraint ?? defaultConstraint);
    }

    internal static void EmitDecorateServiceCore(StringBuilder sb)
    {
        sb.AppendIndentedLine(1, "private static void DecorateService<TRequest, TResponse,");
        sb.AppendIndentedLine(2, "[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(");
        sb.AppendIndentedLine(3,
            "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)] TDecorator>(");
        sb.AppendIndentedLine(2, "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendIndentedLine(2, "where TRequest : global::DecoratR.IRequest");
        sb.AppendIndentedLine(2, "where TDecorator : global::DecoratR.IRequestHandler<TRequest, TResponse>");
        sb.AppendIndentedLine(1, "{");
        sb.AppendIndentedLine(2, "var serviceType = typeof(global::DecoratR.IRequestHandler<TRequest, TResponse>);");
        EmitDecorateLogic(sb);
        sb.AppendIndentedLine(1, "}");
    }

    internal static void EmitDecorateStreamServiceCore(StringBuilder sb)
    {
        sb.AppendIndentedLine(1, "private static void DecorateStreamService<TRequest, TResponse,");
        sb.AppendIndentedLine(2, "[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(");
        sb.AppendIndentedLine(3,
            "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)] TDecorator>(");
        sb.AppendIndentedLine(2, "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendIndentedLine(2, "where TRequest : global::DecoratR.IStreamRequest");
        sb.AppendIndentedLine(2, "where TDecorator : global::DecoratR.IStreamRequestHandler<TRequest, TResponse>");
        sb.AppendIndentedLine(1, "{");
        sb.AppendIndentedLine(2, "var serviceType = typeof(global::DecoratR.IStreamRequestHandler<TRequest, TResponse>);");
        EmitDecorateLogic(sb);
        sb.AppendIndentedLine(1, "}");
    }

    private static void EmitDecorateLogic(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendIndentedLine(2,
            "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor? wrappedDescriptor = null;");
        sb.AppendIndentedLine(2, "int index = -1;");
        sb.AppendIndentedLine(2, "for (int i = 0; i < services.Count; i++)");
        sb.AppendIndentedLine(2, "{");
        sb.AppendIndentedLine(3, "if (services[i].ServiceType == serviceType)");
        sb.AppendIndentedLine(3, "{");
        sb.AppendIndentedLine(4, "wrappedDescriptor = services[i];");
        sb.AppendIndentedLine(4, "index = i;");
        sb.AppendIndentedLine(4, "break;");
        sb.AppendIndentedLine(3, "}");
        sb.AppendIndentedLine(2, "}");
        sb.AppendLine();
        sb.AppendIndentedLine(2, "if (wrappedDescriptor is null)");
        sb.AppendIndentedLine(2, "{");
        sb.AppendIndentedLine(3, "throw new global::System.InvalidOperationException(");
        sb.AppendIndentedLine(4, "$\"No service of type {serviceType.FullName} has been registered.\");");
        sb.AppendIndentedLine(2, "}");
        sb.AppendLine();
        sb.AppendIndentedLine(2, "services.RemoveAt(index);");
        sb.AppendIndentedLine(2,
            "services.Insert(index, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(");
        sb.AppendIndentedLine(3, "serviceType,");
        sb.AppendIndentedLine(3, "provider =>");
        sb.AppendIndentedLine(3, "{");
        sb.AppendIndentedLine(4, "var innerInstance = wrappedDescriptor.ImplementationFactory is not null");
        sb.AppendIndentedLine(5, "? wrappedDescriptor.ImplementationFactory(provider)");
        sb.AppendIndentedLine(5, ": wrappedDescriptor.ImplementationInstance ??");
        sb.AppendIndentedLine(6, "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(");
        sb.AppendIndentedLine(7, "provider, wrappedDescriptor.ImplementationType!);");
        sb.AppendLine();
        sb.AppendIndentedLine(4,
            "return global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(");
        sb.AppendIndentedLine(5, "provider, typeof(TDecorator), innerInstance);");
        sb.AppendIndentedLine(3, "},");
        sb.AppendIndentedLine(3, "wrappedDescriptor.Lifetime));");
    }

    internal static string GetApplyMethodName(DecoratorMetadata decorator)
    {
        var name = decorator.DecoratorFullyQualifiedName;

        // Strip "global::" prefix
        if (name.StartsWith("global::", StringComparison.OrdinalIgnoreCase))
            name = name.Substring("global::".Length);

        // Replace dots with underscores to preserve namespace uniqueness
        // (e.g. App.LoggingDecorator and Infra.LoggingDecorator produce
        //  ApplyApp_LoggingDecorator and ApplyInfra_LoggingDecorator)
        name = name.Replace('.', '_');

        var prefix = decorator.IsStream ? "ApplyStream" : "Apply";
        return string.Concat(prefix, name);
    }

    private static bool HasNonDefaultConstraints(EquatableArray<string> constraintTypes, bool isStream)
    {
        if (constraintTypes.Length == 0) return false;

        var defaultMarker = isStream ? "global::DecoratR.IStreamRequest" : "global::DecoratR.IRequest";
        foreach (var c in constraintTypes)
            if (c != defaultMarker && c != "global::DecoratR.IRequest")
                return true;

        return false;
    }

    private static void AppendSemicolonDelimited(StringBuilder sb, EquatableArray<string> items)
    {
        for (var i = 0; i < items.Length; i++)
        {
            if (i > 0) sb.Append(';');
            sb.Append(items[i]);
        }
    }
}