using System.Text;

namespace DecoratR.Generator;

internal static class DecoratorRegistryEmitter
{
    internal static string Generate(string assemblyName, IReadOnlyList<DecoratorMetadata> decorators)
    {
        var sb = new StringBuilder(512 + decorators.Count * 600);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This file was generated by DecoratR.Generator.");
        sb.AppendLine("//     Do not edit. Changes will be overwritten on the next build.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0612, CS0618 // Type or member is obsolete");
        sb.AppendLine();

        // Assembly-level metadata attributes for each decorator
        foreach (var decorator in decorators)
        {
            var methodName = GetApplyMethodName(decorator);
            sb.Append("[assembly: global::DecoratR.DecoratRDecoratorRegistration(\"")
                .Append(assemblyName).Append(".DecoratRDecoratorRegistry.").Append(methodName)
                .Append("\", ")
                .Append(decorator.Order)
                .AppendLine(")]");
        }

        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).AppendLine(";");
        sb.AppendLine();

        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"1.0.0\")]");
        sb.AppendLine("public static class DecoratRDecoratorRegistry");
        sb.AppendLine("{");

        // Per-decorator public apply methods
        for (var i = 0; i < decorators.Count; i++)
        {
            if (i > 0)
            {
                sb.AppendLine();
            }

            EmitApplyMethod(sb, decorators[i]);
        }

        sb.AppendLine();

        // Shared private core method that inlines the decoration logic
        EmitDecorateServiceCore(sb);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitApplyMethod(StringBuilder sb, DecoratorMetadata decorator)
    {
        var methodName = GetApplyMethodName(decorator);
        sb.AppendIndentedLine(1, "/// <summary>");
        sb.Append("    /// Wraps <c>IRequestHandler&lt;TRequest, TResponse&gt;</c> with <c>")
            .Append(StripGlobalPrefix(decorator.DecoratorFullyQualifiedName))
            .AppendLine("</c>.");
        sb.AppendIndentedLine(1, "/// </summary>");
        sb.Append("    /// <remarks>Decorator order: <c>").Append(decorator.Order).AppendLine("</c>.</remarks>");
        sb.Append("    public static void ").Append(methodName).AppendLine("<TRequest, TResponse>(");
        sb.AppendIndentedLine(2, "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendIndentedLine(2, "where TRequest : global::DecoratR.IRequest");
        sb.AppendIndentedLine(1, "{");
        sb.Append("        DecorateService<TRequest, TResponse, ")
            .Append(decorator.DecoratorFullyQualifiedName)
            .AppendLine("<TRequest, TResponse>>(services);");
        sb.AppendIndentedLine(1, "}");
    }

    internal static void EmitDecorateServiceCore(StringBuilder sb)
    {
        sb.AppendIndentedLine(1, "private static void DecorateService<TRequest, TResponse,");
        sb.AppendIndentedLine(2, "[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(");
        sb.AppendIndentedLine(3, "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)] TDecorator>(");
        sb.AppendIndentedLine(2, "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendIndentedLine(2, "where TRequest : global::DecoratR.IRequest");
        sb.AppendIndentedLine(2, "where TDecorator : global::DecoratR.IRequestHandler<TRequest, TResponse>");
        sb.AppendIndentedLine(1, "{");
        sb.AppendIndentedLine(2, "var serviceType = typeof(global::DecoratR.IRequestHandler<TRequest, TResponse>);");
        sb.AppendLine();
        sb.AppendIndentedLine(2, "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor? wrappedDescriptor = null;");
        sb.AppendIndentedLine(2, "int index = -1;");
        sb.AppendIndentedLine(2, "for (int i = 0; i < services.Count; i++)");
        sb.AppendIndentedLine(2, "{");
        sb.AppendIndentedLine(3, "if (services[i].ServiceType == serviceType)");
        sb.AppendIndentedLine(3, "{");
        sb.AppendIndentedLine(4, "wrappedDescriptor = services[i];");
        sb.AppendIndentedLine(4, "index = i;");
        sb.AppendIndentedLine(4, "break;");
        sb.AppendIndentedLine(3, "}");
        sb.AppendIndentedLine(2, "}");
        sb.AppendLine();
        sb.AppendIndentedLine(2, "if (wrappedDescriptor is null)");
        sb.AppendIndentedLine(2, "{");
        sb.AppendIndentedLine(3, "throw new global::System.InvalidOperationException(");
        sb.AppendIndentedLine(4, "$\"No service of type {serviceType.FullName} has been registered.\");");
        sb.AppendIndentedLine(2, "}");
        sb.AppendLine();
        sb.AppendIndentedLine(2, "services.RemoveAt(index);");
        sb.AppendIndentedLine(2, "services.Insert(index, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(");
        sb.AppendIndentedLine(3, "serviceType,");
        sb.AppendIndentedLine(3, "provider =>");
        sb.AppendIndentedLine(3, "{");
        sb.AppendIndentedLine(4, "var innerInstance = wrappedDescriptor.ImplementationFactory is not null");
        sb.AppendIndentedLine(5, "? wrappedDescriptor.ImplementationFactory(provider)");
        sb.AppendIndentedLine(5, ": wrappedDescriptor.ImplementationInstance ??");
        sb.AppendIndentedLine(6, "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(");
        sb.AppendIndentedLine(7, "provider, wrappedDescriptor.ImplementationType!);");
        sb.AppendLine();
        sb.AppendIndentedLine(4, "return global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(");
        sb.AppendIndentedLine(5, "provider, typeof(TDecorator), innerInstance);");
        sb.AppendIndentedLine(3, "},");
        sb.AppendIndentedLine(3, "wrappedDescriptor.Lifetime));");
        sb.AppendIndentedLine(1, "}");
    }

    internal static string GetApplyMethodName(DecoratorMetadata decorator)
    {
        var name = StripGlobalPrefix(decorator.DecoratorFullyQualifiedName);

        // Replace dots with underscores to preserve namespace uniqueness
        // (e.g. App.LoggingDecorator and Infra.LoggingDecorator produce
        //  ApplyApp_LoggingDecorator and ApplyInfra_LoggingDecorator)
        name = name.Replace('.', '_');

        return string.Concat("Apply", name);
    }

    private static string StripGlobalPrefix(string typeName) =>
        typeName.StartsWith("global::", StringComparison.OrdinalIgnoreCase) ? typeName.Substring("global::".Length) : typeName;
}