using System.Collections.Immutable;
using System.Text;

namespace DecoratR.Generator;

internal static class FullRegistrationEmitter
{
    internal static string Generate(
        string assemblyName,
        IReadOnlyList<HandlerMetadata> localHandlers,
        ImmutableArray<string> referencedRegistryClassNames,
        ImmutableArray<HandlerMetadata> referencedServiceTypes,
        IReadOnlyList<DecoratorMetadata> localDecorators,
        ImmutableArray<ReferencedDecoratorInfo> referencedDecorators,
        IReadOnlyList<HandlerMetadata> localStreamHandlers,
        ImmutableArray<HandlerMetadata> referencedStreamServiceTypes,
        IReadOnlyList<DecoratorMetadata> localStreamDecorators,
        ImmutableArray<ReferencedDecoratorInfo> referencedStreamDecorators)
    {
        var totalDecoratorCount = localDecorators.Count + referencedDecorators.Length
            + localStreamDecorators.Count + referencedStreamDecorators.Length;
        var totalHandlerCount = localHandlers.Count + referencedServiceTypes.Length
            + localStreamHandlers.Count + referencedStreamServiceTypes.Length;
        var sb = new StringBuilder(512 + totalHandlerCount * 300 + totalDecoratorCount * 200);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This file was generated by DecoratR.Generator.");
        sb.AppendLine("//     Do not edit. Changes will be overwritten on the next build.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0612, CS0618 // Type or member is obsolete");
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).AppendLine(";");
        sb.AppendLine();

        sb.Append("[global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"")
            .Append(DecoratRGeneratorVersion.Value).AppendLine("\")]");
        sb.AppendLine("public static class DecoratRServiceCollectionExtensions");
        sb.AppendLine("{");

        var regularHandlerCount = localHandlers.Count + referencedServiceTypes.Length;
        var regularDecoratorCount = localDecorators.Count + referencedDecorators.Length;
        var streamHandlerCount = localStreamHandlers.Count + referencedStreamServiceTypes.Length;
        var streamDecoratorCount = localStreamDecorators.Count + referencedStreamDecorators.Length;

        sb.AppendIndentedLine(1, "/// <summary>");
        sb.Append("    /// Registers ")
            .Append(regularHandlerCount)
            .Append(" handler(s), ")
            .Append(regularDecoratorCount)
            .Append(" decorator(s), ")
            .Append(streamHandlerCount)
            .Append(" stream handler(s), and ")
            .Append(streamDecoratorCount)
            .AppendLine(" stream decorator(s) discovered across the compilation.");
        sb.AppendIndentedLine(1, "/// </summary>");

        sb.AppendIndentedLine(1,
            "public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDecoratR(");
        sb.AppendIndentedLine(2, "this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendIndentedLine(2,
            "global::System.Action<global::DecoratR.DecoratROptions>? configure = null)");
        sb.AppendIndentedLine(1, "{");
        sb.AppendIndentedLine(2, "var options = new global::DecoratR.DecoratROptions();");
        sb.AppendIndentedLine(2, "configure?.Invoke(options);");
        sb.AppendLine();

        EmitReferencedHandlerRegistrations(sb, referencedRegistryClassNames);
        EmitLocalHandlerRegistrations(sb, localHandlers, referencedRegistryClassNames.Length > 0);
        EmitDecoratorApplications(sb, localHandlers, referencedServiceTypes, localDecorators, referencedDecorators);

        // Stream handlers
        var hasRegularContent = referencedRegistryClassNames.Length > 0 || localHandlers.Count > 0;
        EmitReferencedStreamHandlerRegistrations(sb, referencedRegistryClassNames, hasRegularContent);
        EmitLocalStreamHandlerRegistrations(sb, localStreamHandlers,
            hasRegularContent || referencedRegistryClassNames.Length > 0);
        EmitStreamDecoratorApplications(sb, localStreamHandlers, referencedStreamServiceTypes,
            localStreamDecorators, referencedStreamDecorators);

        sb.AppendLine();
        sb.AppendIndentedLine(2, "return services;");
        sb.AppendIndentedLine(1, "}");

        var hasLocalRegularDecorators = false;
        var hasLocalStreamDecorators = false;
        foreach (var d in localDecorators)
            if (!d.IsStream) { hasLocalRegularDecorators = true; break; }
        foreach (var d in localStreamDecorators)
            if (d.IsStream) { hasLocalStreamDecorators = true; break; }

        // Also check the main decorator list for any regular
        if (!hasLocalRegularDecorators)
            foreach (var d in localDecorators)
                if (!d.IsStream) { hasLocalRegularDecorators = true; break; }

        if (hasLocalRegularDecorators)
        {
            sb.AppendLine();
            DecoratorRegistryEmitter.EmitDecorateServiceCore(sb);
        }

        if (hasLocalStreamDecorators)
        {
            sb.AppendLine();
            DecoratorRegistryEmitter.EmitDecorateStreamServiceCore(sb);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitReferencedHandlerRegistrations(
        StringBuilder sb, ImmutableArray<string> registryClassNames)
    {
        if (registryClassNames.Length == 0) return;

        sb.AppendIndentedLine(2, "// Register handlers from referenced assemblies");

        foreach (var registryClassName in registryClassNames)
        {
            sb.Append("        foreach (var handler in global::").Append(registryClassName).AppendLine(".Handlers)");
            sb.AppendIndentedLine(2, "{");
            sb.AppendIndentedLine(3,
                "services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
            sb.AppendIndentedLine(4, "handler.ServiceType,");
            sb.AppendIndentedLine(4, "handler.ImplementationType,");
            sb.AppendIndentedLine(4, "options.Lifetime));");
            sb.AppendIndentedLine(2, "}");
        }
    }

    private static void EmitReferencedStreamHandlerRegistrations(
        StringBuilder sb, ImmutableArray<string> registryClassNames, bool hasPreviousContent)
    {
        if (registryClassNames.Length == 0) return;

        if (hasPreviousContent) sb.AppendLine();

        sb.AppendIndentedLine(2, "// Register stream handlers from referenced assemblies");

        foreach (var registryClassName in registryClassNames)
        {
            sb.Append("        foreach (var handler in global::").Append(registryClassName).AppendLine(".StreamHandlers)");
            sb.AppendIndentedLine(2, "{");
            sb.AppendIndentedLine(3,
                "services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
            sb.AppendIndentedLine(4, "handler.ServiceType,");
            sb.AppendIndentedLine(4, "handler.ImplementationType,");
            sb.AppendIndentedLine(4, "options.Lifetime));");
            sb.AppendIndentedLine(2, "}");
        }
    }

    private static void EmitLocalHandlerRegistrations(
        StringBuilder sb, IReadOnlyList<HandlerMetadata> localHandlers, bool hasReferenced)
    {
        if (localHandlers.Count == 0) return;

        if (hasReferenced) sb.AppendLine();

        sb.AppendIndentedLine(2, "// Register local handlers");

        foreach (var handler in localHandlers)
        {
            sb.AppendIndentedLine(2,
                "services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
            sb.Append("            typeof(global::DecoratR.IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .AppendLine(">),");
            sb.Append("            typeof(").Append(handler.HandlerFullyQualifiedName).AppendLine("),");
            sb.AppendIndentedLine(3, "options.Lifetime));");
        }
    }

    private static void EmitLocalStreamHandlerRegistrations(
        StringBuilder sb, IReadOnlyList<HandlerMetadata> localStreamHandlers, bool hasPreviousContent)
    {
        if (localStreamHandlers.Count == 0) return;

        if (hasPreviousContent) sb.AppendLine();

        sb.AppendIndentedLine(2, "// Register local stream handlers");

        foreach (var handler in localStreamHandlers)
        {
            sb.AppendIndentedLine(2,
                "services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
            sb.Append("            typeof(global::DecoratR.IStreamRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .AppendLine(">),");
            sb.Append("            typeof(").Append(handler.HandlerFullyQualifiedName).AppendLine("),");
            sb.AppendIndentedLine(3, "options.Lifetime));");
        }
    }

    private static void EmitDecoratorApplications(
        StringBuilder sb,
        IReadOnlyList<HandlerMetadata> localHandlers,
        ImmutableArray<HandlerMetadata> referencedServiceTypes,
        IReadOnlyList<DecoratorMetadata> localDecorators,
        ImmutableArray<ReferencedDecoratorInfo> referencedDecorators)
    {
        if (localDecorators.Count == 0 && referencedDecorators.Length == 0) return;

        EmitDecoratorApplicationsCore(sb, localHandlers, referencedServiceTypes, localDecorators,
            referencedDecorators, "DecorateService", false);
    }

    private static void EmitStreamDecoratorApplications(
        StringBuilder sb,
        IReadOnlyList<HandlerMetadata> localStreamHandlers,
        ImmutableArray<HandlerMetadata> referencedStreamServiceTypes,
        IReadOnlyList<DecoratorMetadata> localStreamDecorators,
        ImmutableArray<ReferencedDecoratorInfo> referencedStreamDecorators)
    {
        if (localStreamDecorators.Count == 0 && referencedStreamDecorators.Length == 0) return;

        EmitDecoratorApplicationsCore(sb, localStreamHandlers, referencedStreamServiceTypes,
            localStreamDecorators, referencedStreamDecorators, "DecorateStreamService", true);
    }

    private static void EmitDecoratorApplicationsCore(
        StringBuilder sb,
        IReadOnlyList<HandlerMetadata> localHandlers,
        ImmutableArray<HandlerMetadata> referencedServiceTypes,
        IReadOnlyList<DecoratorMetadata> localDecorators,
        ImmutableArray<ReferencedDecoratorInfo> referencedDecorators,
        string decorateMethodName,
        bool isStream)
    {
        // Build service type list with hierarchy lookup
        var totalHandlerCount = localHandlers.Count + referencedServiceTypes.Length;
        var serviceTypeMap = new Dictionary<(string Request, string Response), HashSet<string>>(totalHandlerCount);

        foreach (var h in localHandlers)
        {
            var key = (h.RequestFullyQualifiedName, h.ResponseFullyQualifiedName);
            if (!serviceTypeMap.ContainsKey(key))
                serviceTypeMap[key] = BuildHierarchySet(h.RequestTypeHierarchy);
        }

        foreach (var h in referencedServiceTypes)
        {
            var key = (h.RequestFullyQualifiedName, h.ResponseFullyQualifiedName);
            if (!serviceTypeMap.ContainsKey(key))
                serviceTypeMap[key] = BuildHierarchySet(h.RequestTypeHierarchy);
        }

        if (serviceTypeMap.Count == 0) return;

        var allServiceTypes = new List<(string Request, string Response)>(serviceTypeMap.Keys);
        allServiceTypes.Sort((a, b) =>
        {
            var cmp = string.Compare(a.Request, b.Request, StringComparison.Ordinal);
            return cmp != 0 ? cmp : string.Compare(a.Response, b.Response, StringComparison.Ordinal);
        });

        // Merge local and referenced decorators into a single ordered list
        var allDecorators = new List<(int Order, string Name, bool IsLocal, EquatableArray<string> Constraints)>(
            localDecorators.Count + referencedDecorators.Length);

        foreach (var d in localDecorators)
            allDecorators.Add((d.Order, d.DecoratorFullyQualifiedName, true, d.RequestConstraintTypes));

        foreach (var d in referencedDecorators)
            allDecorators.Add((d.Order, d.ApplyMethodName, false, d.RequestConstraintTypes));

        allDecorators.Sort((a, b) =>
        {
            var cmp = a.Order.CompareTo(b.Order);
            return cmp != 0 ? cmp : string.Compare(a.Name, b.Name, StringComparison.Ordinal);
        });

        sb.AppendLine();
        var comment = isStream
            ? "// Apply stream decorators (ordered by Order, lowest = outermost)"
            : "// Apply decorators (ordered by Order, lowest = outermost)";
        sb.AppendIndentedLine(2, comment);

        var defaultConstraintMarker = isStream ? "global::DecoratR.IStreamRequest" : "global::DecoratR.IRequest";

        foreach (var (requestType, responseType) in allServiceTypes)
        {
            var hierarchy = serviceTypeMap[(requestType, responseType)];

            for (var i = allDecorators.Count - 1; i >= 0; i--)
            {
                var (_, name, isLocal, constraints) = allDecorators[i];

                if (!SatisfiesConstraints(hierarchy, constraints, defaultConstraintMarker))
                    continue;

                if (isLocal)
                    sb.Append("        ").Append(decorateMethodName).Append('<')
                        .Append(requestType).Append(", ")
                        .Append(responseType).Append(", ")
                        .Append(name).Append('<').Append(requestType).Append(", ").Append(responseType)
                        .AppendLine(">>(services);");
                else
                    sb.Append("        global::").Append(name)
                        .Append('<').Append(requestType).Append(", ").Append(responseType)
                        .AppendLine(">(services);");
            }
        }
    }

    private static HashSet<string> BuildHierarchySet(EquatableArray<string> hierarchy)
    {
        var set = new HashSet<string>(StringComparer.Ordinal);
        foreach (var type in hierarchy) set.Add(type);
        return set;
    }

    private static bool SatisfiesConstraints(HashSet<string> requestHierarchy, EquatableArray<string> constraints,
        string defaultConstraintMarker)
    {
        if (constraints.Length == 0) return true;

        foreach (var constraint in constraints)
        {
            // Default marker is always satisfied by any request type in that pipeline
            if (constraint == defaultConstraintMarker || constraint == "global::DecoratR.IRequest") continue;

            if (!requestHierarchy.Contains(constraint))
                return false;
        }

        return true;
    }
}