using System.Collections.Immutable;
using System.Text;

namespace DecoratR.Generator;

internal static class FullRegistrationEmitter
{
    internal static string Generate(
        string assemblyName,
        IReadOnlyList<HandlerMetadata> localHandlers,
        ImmutableArray<string> referencedRegistryClassNames,
        ImmutableArray<HandlerMetadata> referencedServiceTypes,
        IReadOnlyList<DecoratorMetadata> localDecorators,
        ImmutableArray<DecoratorMetadata> referencedDecorators)
    {
        var allDecorators = CombineDecorators(localDecorators, referencedDecorators);
        var sb = new StringBuilder(512 + localHandlers.Count * 300 + allDecorators.Count * 200);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).AppendLine(";");
        sb.AppendLine();

        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"1.0.0\")]");
        sb.AppendLine("public static class DecoratRServiceCollectionExtensions");
        sb.AppendLine("{");

        sb.AppendIndentedLine(1, "/// <summary>");
        sb.AppendIndentedLine(1, "/// Registers all DecoratR handlers and decorators.");
        sb.AppendIndentedLine(1, "/// </summary>");

        sb.AppendIndentedLine(1, "public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDecoratR(");
        sb.AppendIndentedLine(2, "this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendIndentedLine(1, "{");

        EmitReferencedHandlerRegistrations(sb, referencedRegistryClassNames);
        EmitLocalHandlerRegistrations(sb, localHandlers, referencedRegistryClassNames.Length > 0);
        EmitDecoratorApplications(sb, localHandlers, referencedServiceTypes, allDecorators);

        sb.AppendLine();
        sb.AppendIndentedLine(2, "return services;");
        sb.AppendIndentedLine(1, "}");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitReferencedHandlerRegistrations(
        StringBuilder sb, ImmutableArray<string> registryClassNames)
    {
        if (registryClassNames.Length == 0)
        {
            return;
        }

        sb.AppendIndentedLine(2, "// Register handlers from referenced assemblies");

        foreach (var registryClassName in registryClassNames)
        {
            sb.Append("        foreach (var handler in global::").Append(registryClassName).AppendLine(".Handlers)");
            sb.AppendIndentedLine(2, "{");
            sb.AppendIndentedLine(3, "services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
            sb.AppendIndentedLine(4, "handler.ServiceType,");
            sb.AppendIndentedLine(4, "handler.ImplementationType,");
            sb.AppendIndentedLine(4, "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));");
            sb.AppendIndentedLine(2, "}");
        }
    }

    private static void EmitLocalHandlerRegistrations(
        StringBuilder sb, IReadOnlyList<HandlerMetadata> localHandlers, bool hasReferenced)
    {
        if (localHandlers.Count == 0)
        {
            return;
        }

        if (hasReferenced)
        {
            sb.AppendLine();
        }

        sb.AppendIndentedLine(2, "// Register local handlers");

        foreach (var handler in localHandlers)
        {
            sb.AppendIndentedLine(2, "services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
            sb.Append("            typeof(global::DecoratR.IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .AppendLine(">),");
            sb.Append("            typeof(").Append(handler.HandlerFullyQualifiedName).AppendLine("),");
            sb.AppendIndentedLine(3, "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));");
        }
    }

    private static List<DecoratorMetadata> CombineDecorators(
        IReadOnlyList<DecoratorMetadata> localDecorators,
        ImmutableArray<DecoratorMetadata> referencedDecorators)
    {
        var seen = new HashSet<DecoratorMetadata>();
        var all = new List<DecoratorMetadata>();

        foreach (var d in localDecorators)
        {
            if (seen.Add(d))
            {
                all.Add(d);
            }
        }

        foreach (var d in referencedDecorators)
        {
            if (seen.Add(d))
            {
                all.Add(d);
            }
        }

        all.Sort((a, b) =>
        {
            var cmp = a.Order.CompareTo(b.Order);
            return cmp != 0 ? cmp : string.Compare(a.DecoratorFullyQualifiedName, b.DecoratorFullyQualifiedName, StringComparison.Ordinal);
        });

        return all;
    }

    private static void EmitDecoratorApplications(
        StringBuilder sb,
        IReadOnlyList<HandlerMetadata> localHandlers,
        ImmutableArray<HandlerMetadata> referencedServiceTypes,
        List<DecoratorMetadata> decorators)
    {
        if (decorators.Count == 0)
        {
            return;
        }

        var serviceTypeSet = new HashSet<(string Request, string Response)>();
        foreach (var h in localHandlers)
        {
            serviceTypeSet.Add((h.RequestFullyQualifiedName, h.ResponseFullyQualifiedName));
        }

        foreach (var h in referencedServiceTypes)
        {
            serviceTypeSet.Add((h.RequestFullyQualifiedName, h.ResponseFullyQualifiedName));
        }

        if (serviceTypeSet.Count == 0)
        {
            return;
        }

        var allServiceTypes = new List<(string Request, string Response)>(serviceTypeSet);
        allServiceTypes.Sort((a, b) =>
        {
            var cmp = string.Compare(a.Request, b.Request, StringComparison.Ordinal);
            return cmp != 0 ? cmp : string.Compare(a.Response, b.Response, StringComparison.Ordinal);
        });

        sb.AppendLine();
        sb.AppendIndentedLine(2, "// Apply decorators (ordered by Order, lowest = outermost)");

        foreach (var (requestType, responseType) in allServiceTypes)
        {
            for (var i = decorators.Count - 1; i >= 0; i--)
            {
                var decorator = decorators[i];
                sb.AppendIndentedLine(2, "global::DecoratR.ServiceCollectionExtensions.Decorate<");
                sb.Append("            global::DecoratR.IRequestHandler<")
                    .Append(requestType).Append(", ").Append(responseType).AppendLine(">,");
                sb.Append("            ").Append(decorator.DecoratorFullyQualifiedName)
                    .Append("<").Append(requestType).Append(", ").Append(responseType).AppendLine(">,");
                sb.Append("            ").Append(requestType).AppendLine(",");
                sb.Append("            ").Append(responseType).AppendLine(">(services);");
            }
        }
    }
}