using System.Text;

namespace DecoratR.Generator;

internal static class HandlerRegistryEmitter
{
    internal static string Generate(string assemblyName, IReadOnlyList<HandlerMetadata> handlers)
    {
        var registryClassName = string.Concat(assemblyName, ".DecoratRHandlerRegistry");
        var sb = new StringBuilder(300 + handlers.Count * 500);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This file was generated by DecoratR.Generator.");
        sb.AppendLine("//     Do not edit. Changes will be overwritten on the next build.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0612, CS0618 // Type or member is obsolete");
        sb.AppendLine();

        // Assembly-level metadata attributes
        sb.Append("[assembly: global::DecoratR.DecoratRHandlerRegistration(\"")
            .Append(registryClassName)
            .AppendLine("\")]");

        foreach (var handler in handlers)
        {
            sb.Append("[assembly: global::DecoratR.DecoratRHandlerServiceType(\"")
                .Append(handler.RequestFullyQualifiedName)
                .Append("\", \"")
                .Append(handler.ResponseFullyQualifiedName)
                .Append('"');

            var hierarchyStr = BuildHierarchyString(handler.RequestTypeHierarchy);
            if (hierarchyStr.Length > 0)
                sb.Append(", RequestTypeHierarchy = \"").Append(hierarchyStr).Append('"');

            sb.AppendLine(")]");
        }

        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).AppendLine(";");
        sb.AppendLine();

        sb.Append("[global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"")
            .Append(DecoratRGeneratorVersion.Value).AppendLine("\")]");
        sb.AppendLine("public static class DecoratRHandlerRegistry");
        sb.AppendLine("{");

        // XML summary
        sb.AppendIndentedLine(1, "/// <summary>");
        sb.Append("    /// ").Append(handlers.Count).Append(" handler(s) discovered in <c>").Append(assemblyName)
            .AppendLine("</c>.");
        sb.AppendIndentedLine(1, "/// <list type=\"bullet\">");

        foreach (var handler in handlers)
            sb.Append("    /// <item><description><c>")
                .Append(StripGlobalPrefix(handler.HandlerFullyQualifiedName))
                .Append("</c> handles <c>IRequestHandler&lt;")
                .Append(StripGlobalPrefix(handler.RequestFullyQualifiedName))
                .Append(", ")
                .Append(StripGlobalPrefix(handler.ResponseFullyQualifiedName))
                .AppendLine("&gt;</c></description></item>");

        sb.AppendIndentedLine(1, "/// </list>");
        sb.AppendIndentedLine(1, "/// </summary>");

        sb.AppendIndentedLine(1, "public static HandlerRegistration[] Handlers { get; } =");
        sb.AppendIndentedLine(1, "[");

        foreach (var handler in handlers)
            sb.Append("        new(typeof(global::DecoratR.IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append(">), typeof(")
                .Append(handler.HandlerFullyQualifiedName)
                .AppendLine(")),");

        sb.AppendIndentedLine(1, "];");
        sb.AppendLine();
        sb.AppendIndentedLine(1, "public sealed record HandlerRegistration(");
        sb.AppendIndentedLine(2, "global::System.Type ServiceType,");
        sb.AppendIndentedLine(2,
            "[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        sb.AppendIndentedLine(2,
            "[property: global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        sb.AppendIndentedLine(2,
            "global::System.Type ImplementationType);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string BuildHierarchyString(EquatableArray<string> hierarchy)
    {
        if (hierarchy.Length == 0) return "";

        var sb = new StringBuilder();
        var first = true;
        foreach (var type in hierarchy)
        {
            if (!first) sb.Append(';');
            sb.Append(type);
            first = false;
        }

        return sb.ToString();
    }

    private static string StripGlobalPrefix(string typeName)
    {
        return typeName.StartsWith("global::", StringComparison.OrdinalIgnoreCase)
            ? typeName.Substring("global::".Length)
            : typeName;
    }
}