using System.Text;

namespace DecoratR.Generator;

internal static class SourceGenerationHelper
{
    internal static string GenerateAttribute() =>
        @"// <auto-generated />
#nullable enable

namespace DecoratR
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
    internal sealed class GenerateHandlerRegistrationsAttribute : global::System.Attribute
    {
    }
}
";

    internal static string GenerateRegistrations(string assemblyName, IReadOnlyList<HandlerMetadata> handlers)
    {
        var sanitizedName = SanitizeAssemblyName(assemblyName);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace DecoratR.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Compile-time discovered handler registrations for assembly '{assemblyName}'.");
        sb.AppendLine("    /// Generated by DecoratR.Generator.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"1.0.0\")]");
        sb.AppendLine($"    public static class {sanitizedName}Registrations");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers all discovered handlers, replacing the need for runtime assembly scanning.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::DecoratR.DecoratROptions RegisterHandlers(this global::DecoratR.DecoratROptions options)");
        sb.AppendLine("        {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"            // {GetCategoryComment(handler.Category)}");
            sb.AppendLine($"            options.AddHandler<{handler.RequestFullyQualifiedName}, {handler.ResponseFullyQualifiedName}, {handler.HandlerFullyQualifiedName}>();");
        }

        sb.AppendLine("            return options;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string SanitizeAssemblyName(string assemblyName)
    {
        var sb = new StringBuilder(assemblyName.Length);
        foreach (var c in assemblyName)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        // Ensure it doesn't start with a digit
        if (sb.Length > 0 && char.IsDigit(sb[0]))
        {
            sb.Insert(0, '_');
        }

        return sb.ToString();
    }

    private static string GetCategoryComment(RequestCategory category)
    {
        switch (category)
        {
            case RequestCategory.Command: return "Command handler";
            case RequestCategory.Query: return "Query handler";
            default: return "Request handler";
        }
    }
}