using System.Text;

namespace DecoratR.Generator;

internal static class SourceGenerationHelper
{
    internal static string GenerateAttribute() =>
        @"// <auto-generated />
#nullable enable

namespace DecoratR
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
    internal sealed class GenerateHandlerRegistrationsAttribute : global::System.Attribute
    {
    }
}
";

    internal static string GenerateRegistrations(string assemblyName, IReadOnlyList<HandlerMetadata> handlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Compile-time discovered handler registrations for assembly '{assemblyName}'.");
        sb.AppendLine("    /// Generated by DecoratR.Generator.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"1.0.0\")]");
        sb.AppendLine("    public static class HandlerRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// All compile-time discovered handler registrations as (ServiceType, ImplementationType) tuples.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::System.Collections.Generic.List<(global::System.Type ServiceType, global::System.Type ImplementationType)> Handlers { get; } =");
        sb.AppendLine("        [");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"            (typeof(global::DecoratR.IRequestHandler<{handler.RequestFullyQualifiedName}, {handler.ResponseFullyQualifiedName}>), typeof({handler.HandlerFullyQualifiedName})),");
        }

        sb.AppendLine("        ];");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

}