using System.Text;

namespace DecoratR.Generator;

internal static class SourceGenerationHelper
{
    internal static string GenerateHandlerAttribute() =>
        """
        // <auto-generated />
        #nullable enable

        namespace DecoratR;

        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateHandlerRegistrationsAttribute : global::System.Attribute
        {
        }
        """;

    internal static string GenerateFullAttribute() =>
        """
        // <auto-generated />
        #nullable enable

        namespace DecoratR;

        /// <summary>
        /// Triggers the DecoratR source generator to discover all handlers and decorators in the compilation
        /// and emit an <c>AddDecoratR()</c> extension method on <c>IServiceCollection</c>.
        /// Place this attribute in the composition root assembly (e.g. the web API project).
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDecoratRRegistrationsAttribute : global::System.Attribute
        {
        }
        """;

    internal static string GenerateHandlerRegistrationAttribute() =>
        """
        // <auto-generated />
        #nullable enable

        namespace DecoratR;

        /// <summary>
        /// Assembly-level attribute that encodes the fully qualified class name
        /// of a generated handler registry containing a <c>Handlers</c> property.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
        internal sealed class DecoratRHandlerRegistrationAttribute : global::System.Attribute
        {
            public DecoratRHandlerRegistrationAttribute(string className)
            {
                ClassName = className;
            }

            public string ClassName { get; }
        }
        """;

    internal static string GenerateHandlerServiceTypeAttribute() =>
        """
        // <auto-generated />
        #nullable enable

        namespace DecoratR;

        /// <summary>
        /// Assembly-level attribute that encodes a handler's service type (request/response pair).
        /// Used by the composition root generator to discover service types for decorator application.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
        internal sealed class DecoratRHandlerServiceTypeAttribute : global::System.Attribute
        {
            public DecoratRHandlerServiceTypeAttribute(string requestType, string responseType)
            {
                RequestType = requestType;
                ResponseType = responseType;
            }

            public string RequestType { get; }
            public string ResponseType { get; }
        }
        """;

    /// <summary>
    /// Generates a DI-free handler registry class and assembly-level metadata attributes (handler-only path).
    /// The registry exposes a <c>Handlers</c> property with <c>HandlerRegistration</c> records,
    /// so the handler assembly does not need a dependency on <c>Microsoft.Extensions.DependencyInjection.Abstractions</c>.
    /// The <c>HandlerRegistration</c> record annotates <c>ImplementationType</c> with
    /// <c>[DynamicallyAccessedMembers]</c> to support Native AOT / trimming.
    /// </summary>
    internal static string GenerateHandlerRegistry(string assemblyName, IReadOnlyList<HandlerMetadata> handlers)
    {
        var sb = new StringBuilder();
        var registryClassName = $"{assemblyName}.DecoratRHandlerRegistry";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Assembly-level metadata attributes
        sb.AppendLine($"[assembly: global::DecoratR.DecoratRHandlerRegistration(\"{registryClassName}\")]");
        foreach (var handler in handlers)
        {
            sb.AppendLine($"[assembly: global::DecoratR.DecoratRHandlerServiceType(\"{handler.RequestFullyQualifiedName}\", \"{handler.ResponseFullyQualifiedName}\")]");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName};");
        sb.AppendLine();

        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"1.0.0\")]");
        sb.AppendLine("public static class DecoratRHandlerRegistry");
        sb.AppendLine("{");

        // XML summary
        sb.AppendIndentedLine(1, "/// <summary>");
        sb.AppendIndentedLine(1, $"/// {handlers.Count} handler(s) discovered in <c>{assemblyName}</c>.");
        sb.AppendIndentedLine(1, "/// <list type=\"bullet\">");
        foreach (var handler in handlers)
        {
            var handlerName = StripGlobalPrefix(handler.HandlerFullyQualifiedName);
            var requestName = StripGlobalPrefix(handler.RequestFullyQualifiedName);
            var responseName = StripGlobalPrefix(handler.ResponseFullyQualifiedName);
            sb.AppendIndentedLine(1, $"/// <item><description><c>{handlerName}</c> handles <c>IRequestHandler&lt;{requestName}, {responseName}&gt;</c></description></item>");
        }

        sb.AppendIndentedLine(1, "/// </list>");
        sb.AppendIndentedLine(1, "/// </summary>");

        sb.AppendIndentedLine(1, "public static HandlerRegistration[] Handlers { get; } =");
        sb.AppendIndentedLine(1, "[");

        foreach (var handler in handlers)
        {
            sb.AppendIndentedLine(2, $"new(typeof(global::DecoratR.IRequestHandler<{handler.RequestFullyQualifiedName}, {handler.ResponseFullyQualifiedName}>), typeof({handler.HandlerFullyQualifiedName})),");
        }

        sb.AppendIndentedLine(1, "];");
        sb.AppendLine();
        sb.AppendIndentedLine(1, "public sealed record HandlerRegistration(");
        sb.AppendIndentedLine(2, "global::System.Type ServiceType,");
        sb.AppendIndentedLine(2, "[property: global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)] global::System.Type ImplementationType);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the full registration extension method with <c>AddDecoratR()</c>.
    /// </summary>
    internal static string GenerateFullRegistrations(
        string assemblyName,
        IReadOnlyList<HandlerMetadata> localHandlers,
        IReadOnlyList<string> referencedRegistryClassNames,
        IReadOnlyList<HandlerMetadata> referencedServiceTypes,
        IReadOnlyList<DecoratorMetadata> decorators)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName};");
        sb.AppendLine();

        // ── AddDecoratR() extension method ────────────────────────────────────
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DecoratR.Generator\", \"1.0.0\")]");
        sb.AppendLine("public static class DecoratRServiceCollectionExtensions");
        sb.AppendLine("{");

        // XML summary
        sb.AppendIndentedLine(1, "/// <summary>");
        sb.AppendIndentedLine(1, "/// Registers all DecoratR handlers and decorators.");
        sb.AppendIndentedLine(1, "/// </summary>");

        sb.AppendIndentedLine(1, "public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDecoratR(");
        sb.AppendIndentedLine(2, "this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendIndentedLine(1, "{");

        // Register handlers from referenced assembly registries
        if (referencedRegistryClassNames.Count > 0)
        {
            sb.AppendIndentedLine(2, "// Register handlers from referenced assemblies");
            foreach (var registryClassName in referencedRegistryClassNames)
            {
                // sb.AppendLine("#pragma warning disable IL2077 // ImplementationType is always a compile-time typeof() expression");
                sb.AppendIndentedLine(2, $"foreach (var handler in global::{registryClassName}.Handlers)");
                sb.AppendIndentedLine(2, "{");
                sb.AppendIndentedLine(3, "services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
                sb.AppendIndentedLine(4, "handler.ServiceType,");
                sb.AppendIndentedLine(4, "handler.ImplementationType,");
                sb.AppendIndentedLine(4, "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));");
                sb.AppendIndentedLine(2, "}");
                // sb.AppendLine("#pragma warning restore IL2077");
            }
        }

        // Register local handlers
        if (localHandlers.Count > 0)
        {
            if (referencedRegistryClassNames.Count > 0)
            {
                sb.AppendLine();
            }

            sb.AppendIndentedLine(2, "// Register local handlers");
            foreach (var handler in localHandlers)
            {
                sb.AppendIndentedLine(2, "services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
                sb.AppendIndentedLine(3, $"typeof(global::DecoratR.IRequestHandler<{handler.RequestFullyQualifiedName}, {handler.ResponseFullyQualifiedName}>),");
                sb.AppendIndentedLine(3, $"typeof({handler.HandlerFullyQualifiedName}),");
                sb.AppendIndentedLine(3, "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));");
            }
        }

        // Apply decorators
        // Combine local + referenced service types for decorator application
        var allServiceTypes = localHandlers
            .Select(h => (h.RequestFullyQualifiedName, h.ResponseFullyQualifiedName))
            .Concat(referencedServiceTypes.Select(h => (h.RequestFullyQualifiedName, h.ResponseFullyQualifiedName)))
            .Distinct()
            .OrderBy(t => t.RequestFullyQualifiedName)
            .ThenBy(t => t.ResponseFullyQualifiedName)
            .ToList();

        if (decorators.Count > 0 && allServiceTypes.Count > 0)
        {
            sb.AppendLine();
            sb.AppendIndentedLine(2, "// Apply decorators (ordered by Order, lowest = outermost)");

            var reversedDecorators = decorators.Reverse().ToArray();

            foreach (var (requestType, responseType) in allServiceTypes)
            {
                foreach (var decorator in reversedDecorators)
                {
                    sb.AppendIndentedLine(2, "global::DecoratR.ServiceCollectionExtensions.Decorate<");
                    sb.AppendIndentedLine(3, $"global::DecoratR.IRequestHandler<{requestType}, {responseType}>,");
                    sb.AppendIndentedLine(3, $"{decorator.DecoratorFullyQualifiedName}<{requestType}, {responseType}>,");
                    sb.AppendIndentedLine(3, $"{requestType},");
                    sb.AppendIndentedLine(3, $"{responseType}>(services);");
                }
            }
        }

        sb.AppendLine();
        sb.AppendIndentedLine(2, "return services;");
        sb.AppendIndentedLine(1, "}");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string StripGlobalPrefix(string typeName) =>
        typeName.StartsWith("global::") ? typeName.Substring("global::".Length) : typeName;
}