// <auto-generated>
//     This file was generated by DecoratR.Generator.
//     Do not edit. Changes will be overwritten on the next build.
// </auto-generated>
#nullable enable
#pragma warning disable CS0612, CS0618 // Type or member is obsolete
#pragma warning disable CS8631, CS8634, CS8714 // Nullability of type arguments does not match constraints (nullability is not part of the runtime service type)

namespace Microsoft.Extensions.DependencyInjection;

/// <summary>
/// DecoratR registrations generated for assembly <c>Sample.App</c>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("DecoratR.Generator", "<version>")]
public static class DecoratRServiceCollectionExtensions
{
    /// <summary>
    /// Registers 2 handler(s) and applies 3 decorator(s) discovered in this assembly and its references.
    /// Lower <c>Order</c> values are applied further outside; ties are broken by the fully qualified decorator type name.
    /// </summary>
    /// <param name="services">The service collection to add the registrations to.</param>
    /// <param name="configure">Optional callback that configures the <see cref="global::DecoratR.DecoratROptions"/>, e.g. the handler lifetime.</param>
    /// <returns>The same <paramref name="services"/> instance.</returns>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDecoratR(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::DecoratR.DecoratROptions>? configure = null)
    {
        var options = new global::DecoratR.DecoratROptions();
        configure?.Invoke(options);

        // Handlers declared in this assembly
        services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
            typeof(global::DecoratR.IRequestHandler<global::TestCommand, string>),
            typeof(global::TestCommandHandler),
            options.Lifetime));
        services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
            typeof(global::DecoratR.IStreamRequestHandler<global::TestStreamQuery, string>),
            typeof(global::TestStreamQueryHandler),
            options.Lifetime));

        // Decorator pipelines (innermost decorator first, lower Order = further outside)
        Decorate(services, typeof(global::DecoratR.IRequestHandler<global::TestCommand, string>), static descriptor =>
        {
            descriptor = Wrap<global::DecoratR.IRequestHandler<global::TestCommand, string>, global::ValidationDecorator<global::TestCommand, string>>(descriptor); // Order 2
            descriptor = Wrap<global::DecoratR.IRequestHandler<global::TestCommand, string>, global::LoggingDecorator<global::TestCommand, string>>(descriptor); // Order 1
            return descriptor;
        });
        Decorate(services, typeof(global::DecoratR.IStreamRequestHandler<global::TestStreamQuery, string>), static descriptor =>
        {
            descriptor = Wrap<global::DecoratR.IStreamRequestHandler<global::TestStreamQuery, string>, global::StreamLoggingDecorator<global::TestStreamQuery, string>>(descriptor); // Order 1
            return descriptor;
        });

        return services;
    }

    /// <summary>
    /// Replaces every non-keyed registration of <paramref name="serviceType"/> with the descriptor returned by <paramref name="decorate"/>.
    /// </summary>
    private static void Decorate(
        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Type serviceType,
        global::System.Func<global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor> decorate)
    {
        var decorated = false;
        for (var i = 0; i < services.Count; i++)
        {
            var descriptor = services[i];
            if (descriptor.IsKeyedService || descriptor.ServiceType != serviceType)
            {
                continue;
            }

            services[i] = decorate(descriptor);
            decorated = true;
        }

        if (!decorated)
        {
            throw new global::System.InvalidOperationException($"DecoratR: no registration of '{serviceType}' was found to decorate.");
        }
    }

    /// <summary>
    /// Returns a descriptor with the lifetime of <paramref name="inner"/> that resolves <typeparamref name="TDecorator"/>
    /// around the service created by <paramref name="inner"/>. Constructor dependencies are resolved from the provider;
    /// constructor selection happens once per registration, not per resolution.
    /// </summary>
    private static global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor Wrap<TService, [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)] TDecorator>(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor inner)
        where TService : class
        where TDecorator : class, TService
    {
        var innerFactory = CreateInnerFactory(inner);
        var decoratorFactory = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(
            typeof(TDecorator),
            new global::System.Type[] { typeof(TService) });

        return global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
            inner.ServiceType,
            provider => decoratorFactory(provider, new object?[] { innerFactory(provider) }),
            inner.Lifetime);
    }

    /// <summary>
    /// Creates a factory for the service described by <paramref name="descriptor"/>.
    /// </summary>
    private static global::System.Func<global::System.IServiceProvider, object> CreateInnerFactory(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor)
    {
        if (descriptor.ImplementationFactory is not null)
        {
            return descriptor.ImplementationFactory;
        }

        if (descriptor.ImplementationInstance is not null)
        {
            var instance = descriptor.ImplementationInstance;
            return _ => instance;
        }

        var factory = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(
            descriptor.ImplementationType!,
            global::System.Type.EmptyTypes);
        return provider => factory(provider, null);
    }
}