// <auto-generated>
//     This file was generated by DecoratR.Generator.
//     Do not edit. Changes will be overwritten on the next build.
// </auto-generated>
#nullable enable
#pragma warning disable CS0612, CS0618 // Type or member is obsolete
#pragma warning disable CS8631, CS8634, CS8714 // Nullability of type arguments does not match constraints (nullability is not part of the runtime service type)

[assembly: global::DecoratR.Metadata.DecoratRRegistry("global::Sample.Library.DecoratRHandlerRegistry")]
[assembly: global::DecoratR.Metadata.DecoratRHandler("global::Sample.Library.CreateUserHandler", "global::Sample.Library.CreateUser", "int", false, RequestTypeHierarchy = "global::Sample.Library.CreateUser;global::Sample.Library.ICommand;global::DecoratR.IRequest;global::System.IEquatable<global::Sample.Library.CreateUser>;!class", ResponseTypeHierarchy = "int;global::System.IConvertible;global::System.Numerics.ISignedNumber<int>;global::System.Numerics.IBinaryInteger<int>;global::System.Numerics.IBinaryNumber<int>;global::System.Numerics.IBitwiseOperators<int, int, int>;global::System.Numerics.INumber<int>;global::System.IComparable;global::System.IComparable<int>;global::System.Numerics.IComparisonOperators<int, int, bool>;global::System.Numerics.IModulusOperators<int, int, int>;global::System.Numerics.INumberBase<int>;global::System.Numerics.IEqualityOperators<int, int, bool>;global::System.Numerics.IAdditionOperators<int, int, int>;global::System.Numerics.IAdditiveIdentity<int, int>;global::System.Numerics.IDecrementOperators<int>;global::System.Numerics.IDivisionOperators<int, int, int>;global::System.IEquatable<int>;global::System.Numerics.IIncrementOperators<int>;global::System.Numerics.IMultiplicativeIdentity<int, int>;global::System.Numerics.IMultiplyOperators<int, int, int>;global::System.ISpanFormattable;global::System.IFormattable;global::System.ISpanParsable<int>;global::System.IParsable<int>;global::System.Numerics.ISubtractionOperators<int, int, int>;global::System.Numerics.IUnaryPlusOperators<int, int>;global::System.Numerics.IUnaryNegationOperators<int, int>;global::System.IUtf8SpanFormattable;global::System.IUtf8SpanParsable<int>;global::System.Numerics.IShiftOperators<int, int, int>;global::System.Numerics.IMinMaxValue<int>;global::System.ValueType;!struct;!unmanaged;!new")]
[assembly: global::DecoratR.Metadata.DecoratRHandler("global::Sample.Library.GetUsersHandler", "global::Sample.Library.GetUsers", "global::System.Collections.Generic.IReadOnlyList<string>", false, RequestTypeHierarchy = "global::Sample.Library.GetUsers;global::DecoratR.IRequest;global::System.IEquatable<global::Sample.Library.GetUsers>;!class;!new", ResponseTypeHierarchy = "global::System.Collections.Generic.IReadOnlyList<string>;global::System.Collections.Generic.IReadOnlyCollection<string>;global::System.Collections.Generic.IEnumerable<string>;global::System.Collections.IEnumerable;!class")]
[assembly: global::DecoratR.Metadata.DecoratRHandler("global::Sample.Library.StreamUsersHandler", "global::Sample.Library.StreamUsers", "string", true, RequestTypeHierarchy = "global::Sample.Library.StreamUsers;global::DecoratR.IStreamRequest;global::System.IEquatable<global::Sample.Library.StreamUsers>;!class;!new", ResponseTypeHierarchy = "string;global::System.IComparable;global::System.IConvertible;global::System.Collections.Generic.IEnumerable<char>;global::System.Collections.IEnumerable;global::System.IComparable<string?>;global::System.IEquatable<string?>;global::System.ICloneable;global::System.ISpanParsable<string>;global::System.IParsable<string>;!class")]

namespace Sample.Library;

/// <summary>
/// Handler registry generated by DecoratR for assembly <c>Sample.Library</c>.
/// Infrastructure for cross-assembly composition; not intended for direct use.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("DecoratR.Generator", "<version>")]
[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
public static class DecoratRHandlerRegistry
{
    /// <summary>
    /// 3 handler(s) discovered in this assembly:
    /// <list type="bullet">
    /// <item><description><c>Sample.Library.CreateUserHandler</c> implements <c>DecoratR.IRequestHandler&lt;Sample.Library.CreateUser, int&gt;</c></description></item>
    /// <item><description><c>Sample.Library.GetUsersHandler</c> implements <c>DecoratR.IRequestHandler&lt;Sample.Library.GetUsers, System.Collections.Generic.IReadOnlyList&lt;string&gt;&gt;</c></description></item>
    /// <item><description><c>Sample.Library.StreamUsersHandler</c> implements <c>DecoratR.IStreamRequestHandler&lt;Sample.Library.StreamUsers, string&gt;</c></description></item>
    /// </list>
    /// </summary>
    public static HandlerRegistration[] Handlers { get; } =
    [
        new(typeof(global::DecoratR.IRequestHandler<global::Sample.Library.CreateUser, int>), typeof(global::Sample.Library.CreateUserHandler)),
        new(typeof(global::DecoratR.IRequestHandler<global::Sample.Library.GetUsers, global::System.Collections.Generic.IReadOnlyList<string>>), typeof(global::Sample.Library.GetUsersHandler)),
        new(typeof(global::DecoratR.IStreamRequestHandler<global::Sample.Library.StreamUsers, string>), typeof(global::Sample.Library.StreamUsersHandler)),
    ];

    /// <summary>The service type and implementation type of one registered handler.</summary>
    public sealed record HandlerRegistration(
        global::System.Type ServiceType,
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)] [property: global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)] global::System.Type ImplementationType);
}