// <auto-generated>
//     This file was generated by DecoratR.Generator.
//     Do not edit. Changes will be overwritten on the next build.
// </auto-generated>
#nullable enable
#pragma warning disable CS0612, CS0618 // Type or member is obsolete
#pragma warning disable CS8631, CS8634, CS8714 // Nullability of type arguments does not match constraints (nullability is not part of the runtime service type)

[assembly: global::DecoratR.Metadata.DecoratRDecorator("global::Sample.Library.DecoratRDecoratorRegistry.ApplySample_Library_LoggingDecorator", "global::Sample.Library.LoggingDecorator", 1, false, RequestConstraints = "global::DecoratR.IRequest")]
[assembly: global::DecoratR.Metadata.DecoratRDecorator("global::Sample.Library.DecoratRDecoratorRegistry.ApplySample_Library_StreamLoggingDecorator", "global::Sample.Library.StreamLoggingDecorator", 1, true, RequestConstraints = "global::DecoratR.IStreamRequest")]
[assembly: global::DecoratR.Metadata.DecoratRDecorator("global::Sample.Library.DecoratRDecoratorRegistry.ApplySample_Library_CommandDecorator", "global::Sample.Library.CommandDecorator", 2, false, RequestConstraints = "!class;global::Sample.Library.ICommand", ResponseConstraints = "!struct")]

namespace Sample.Library;

/// <summary>
/// Decorator registry generated by DecoratR for assembly <c>Sample.Library</c>.
/// Infrastructure for cross-assembly composition; not intended for direct use.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("DecoratR.Generator", "<version>")]
[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
public static class DecoratRDecoratorRegistry
{
    /// <summary>
    /// Wraps a <c>DecoratR.IRequestHandler&lt;TRequest, TResponse&gt;</c> registration with <c>Sample.Library.LoggingDecorator&lt;TRequest, TResponse&gt;</c> (Order 1).
    /// </summary>
    public static global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor ApplySample_Library_LoggingDecorator<TRequest, TResponse>(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor inner)
        where TRequest : global::DecoratR.IRequest
    {
        return Wrap<global::DecoratR.IRequestHandler<TRequest, TResponse>, global::Sample.Library.LoggingDecorator<TRequest, TResponse>>(inner);
    }

    /// <summary>
    /// Wraps a <c>DecoratR.IStreamRequestHandler&lt;TRequest, TResponse&gt;</c> registration with <c>Sample.Library.StreamLoggingDecorator&lt;TRequest, TResponse&gt;</c> (Order 1).
    /// </summary>
    public static global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor ApplySample_Library_StreamLoggingDecorator<TRequest, TResponse>(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor inner)
        where TRequest : global::DecoratR.IStreamRequest
    {
        return Wrap<global::DecoratR.IStreamRequestHandler<TRequest, TResponse>, global::Sample.Library.StreamLoggingDecorator<TRequest, TResponse>>(inner);
    }

    /// <summary>
    /// Wraps a <c>DecoratR.IRequestHandler&lt;TRequest, TResponse&gt;</c> registration with <c>Sample.Library.CommandDecorator&lt;TRequest, TResponse&gt;</c> (Order 2).
    /// </summary>
    public static global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor ApplySample_Library_CommandDecorator<TRequest, TResponse>(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor inner)
        where TRequest : class, global::Sample.Library.ICommand
        where TResponse : struct
    {
        return Wrap<global::DecoratR.IRequestHandler<TRequest, TResponse>, global::Sample.Library.CommandDecorator<TRequest, TResponse>>(inner);
    }

    /// <summary>
    /// Returns a descriptor with the lifetime of <paramref name="inner"/> that resolves <typeparamref name="TDecorator"/>
    /// around the service created by <paramref name="inner"/>. Constructor dependencies are resolved from the provider;
    /// constructor selection happens once per registration, not per resolution.
    /// </summary>
    private static global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor Wrap<TService, [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)] TDecorator>(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor inner)
        where TService : class
        where TDecorator : class, TService
    {
        var innerFactory = CreateInnerFactory(inner);
        var decoratorFactory = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(
            typeof(TDecorator),
            new global::System.Type[] { typeof(TService) });

        return global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
            inner.ServiceType,
            provider => decoratorFactory(provider, new object?[] { innerFactory(provider) }),
            inner.Lifetime);
    }

    /// <summary>
    /// Creates a factory for the service described by <paramref name="descriptor"/>.
    /// </summary>
    private static global::System.Func<global::System.IServiceProvider, object> CreateInnerFactory(
        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor)
    {
        if (descriptor.ImplementationFactory is not null)
        {
            return descriptor.ImplementationFactory;
        }

        if (descriptor.ImplementationInstance is not null)
        {
            var instance = descriptor.ImplementationInstance;
            return _ => instance;
        }

        var factory = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(
            descriptor.ImplementationType!,
            global::System.Type.EmptyTypes);
        return provider => factory(provider, null);
    }
}