using Examples.ModularMonolith.Api;
using Examples.ModularMonolith.Catalog.Infrastructure;
using Examples.ModularMonolith.Catalog.Presentation;
using Examples.ModularMonolith.Orders.Infrastructure;
using Examples.ModularMonolith.Orders.Presentation;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<ValidationExceptionHandler>();
builder.Services.AddOpenApi();

// Generated by DecoratR: registers every handler of the shared kernel and of all referenced modules and
// wires the decorator pipelines (logging -> query timing -> module audit -> validation -> handler).
builder.Services.AddDecoratR();

// Each module contributes its own infrastructure and application services.
builder.Services.AddCatalogModule();
builder.Services.AddOrdersModule();

var app = builder.Build();

app.UseExceptionHandler();
app.MapOpenApi();

// Each module maps its own endpoints.
app.MapCatalogEndpoints();
app.MapOrdersEndpoints();

app.Run();
