name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Cache NuGet packages
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          key: ${{ github.repository }}-nuget-${{ hashFiles('**/*.csproj') }}
          path: ${{ env.NUGET_PACKAGES }}

      - name: Setup .NET
        uses: fast-actions/setup-dotnet@a71ae3c1c05fa3c6fae4065438844513d41d893e # v1

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build -c Release --no-restore

      - name: Test Solution
        run: dotnet test -c Release --no-build
